export const CAT_FILTER="CAT_FILTER"
export const MOST_EXPENSIVE_FILTER = "MOST_EXPENSIVE_FILTER";
export const CHEAPER_FILTER = "CHEAPER_FILTER";
export const NEWEST_FILTER = "NEWEST_FILTER";
export const OLDEST_FILTER = "OLDEST_FILTER";
export const ONLY_ONE = "ONLY_ONE";